### ISSUE TITLE
No migrations included at initial directory

### ISSUE THREAD

**Issue by OlegKuro** [SymfonyCasts/solid#2]
Hello!

I'm trying to deploy start directory from courses locally and face following problem: migrations file(s) absence.
I've successfully generated my own migration, but probably it would be more handy to include migrations (or notice that in README.md)

**Comment by OlegKuro** [comment]
[created PR to fix this issue](https://github.com/SymfonyCasts/solid/pull/3)

**Comment by MolloKhan** [comment]
Hey @OlegKuro thank you for reporting it and to go one step further by submitting a PR - Unfortunately, I can't merge it because we use an internal tool for managing our courses projects but I'll update this course with migrations. Thanks!
